[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.98.0"
  HUGO_BASEURL = "https://jaufey-blog.netlify.app/"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=600"

[[headers]]
  for = "*.(css|js|woff|woff2|ttf|png|jpg|jpeg)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
